# Generated by Django 4.0.3 on 2022-03-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesearchmodel',
            name='imdbID',
            field=models.CharField(max_length=100),
        ),
    ]
